# Autogenerated file
def render(*a, **d):
    yield """<!DOCTYPE html>
<html lang=\"en\">
  <head>
    <meta charset=\"UTF-8\" />
    <meta name=\"viewport\" content=\"width=device-width + 50, initial-scale=1\" />
    <title>MicroPython WebSocket</title>
    <link rel=\"stylesheet\" href=\"static/index.css\" />
    <link rel=\"icon\" href=\"./favicon.ico\" type=\"image/x-icon\" />
  </head>
  <body>
    <h1>MicroPython WebSocket</h1>
    <script src=\"static/index.js\"></script>
    
    <button class=\"touchpad\" id=\"touchpad\">Правая кнопка мыши</button>
    <button class=\"lkm\" id=\"LKM\">Левая кнопка мыши</button>
    <button class=\"pkm\" id=\"PKM\">Правая кнопка мыши</button>
  </body>
</html>
"""
